Examination_System/Controllers/InstructorCRUDController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;

namespace Examination_System.Controllers
{
    public class InstructorCRUDController : Controller
    {
        ITIContext DB;
        public InstructorCRUDController(ITIContext Db)
        {
            DB = Db;
        }

        public IActionResult ShowInstructors()
        {
            var model = DB.Instructor.ToList();
            return View(model);
        }

        public IActionResult InsertInstructor()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> InsertInstructor(Instructor ins, IFormFile? imageFile)
        {
            string fileImage = imageFile.FileName;
            string fileExt = fileImage.Split('.').Last();
            if (ModelState.IsValid)
            {
                DB.Instructor.Add(ins);
                DB.SaveChanges();
                var instr = DB.Instructor.SingleOrDefault(a => a.Password == ins.Password && a.Email == ins.Email);
                instr.Img_Id = $"{instr.Ins_Id}.{fileExt}";
                using (var fs = new FileStream($"wwwroot/images/Instructors/{instr.Ins_Id}.{fileExt}", FileMode.Create))
                {
                    await imageFile.CopyToAsync(fs);
                }
                DB.Instructor.Update(instr);
                DB.SaveChanges();
                return RedirectToAction("ShowInstructors");
            }
            else
            {
                return View(ins);
            }
        }

        public IActionResult EditInstructor(int id)
        {
            var model = DB.Instructor.SingleOrDefault(i => i.Ins_Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditInstructor(Instructor ins, string OldInsImg, IFormFile? imageFile)
        {
            if (imageFile != null)
            {
                if (System.IO.File.Exists($"wwwroot/images/Instructors/{OldInsImg}"))
                {
                    System.IO.File.Delete($"wwwroot/images/Instructors/{OldInsImg}");
                }
                string fileImage = imageFile.FileName;
                string fileExten = fileImage.Split('.').Last();
                using (var fs = new FileStream($"wwwroot/images/Instructors/{ins.Ins_Id}.{fileExten}", FileMode.Create))
                {
                    await imageFile.CopyToAsync(fs);
                }
                ins.Img_Id = $"{ins.Ins_Id}.{fileExten}";
            }
            else
            {
                ins.Img_Id = OldInsImg;
            }

            DB.Instructor.Update(ins);
            DB.SaveChanges();
            return RedirectToAction("ShowInstructors");
        }

        public IActionResult DeleteInstructor(int id)
        {
            var model = DB.Instructor.SingleOrDefault(a => a.Ins_Id == id);
            if (System.IO.File.Exists($"wwwroot/images/Instructors/{model.Img_Id}"))
            {
                System.IO.File.Delete($"wwwroot/images/Instructors/{model.Img_Id}");
            }
            if (model == null)
            {
                return NotFound();
            }
            var INS_Crs = DB.InstructorCourse.Where(sa => sa.InstructorId == id).ToList();
            foreach (var InsCrs in INS_Crs)
            {

                DB.InstructorCourse.Remove(InsCrs);
            }
            var Track_Ins = DB.Track_Instructor.Where(sa => sa.Ins_Id == id).ToList();
            foreach (var TrcIns in Track_Ins)
            {

                DB.Track_Instructor.Remove(TrcIns);
            }
            var model2= DB.Track.Where(a=>a.Supervisor== id).ToList();
            foreach (var Trc in model2)
            {
                Trc.Supervisor =null;
                DB.SaveChanges();
            }
            DB.Instructor.Remove(model);
            DB.SaveChanges();
            return RedirectToAction("ShowInstructors");
        }
    }
}

Examination_System/Views/InstructorCRUD/EditInstructor.cshtml
@model Instructor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditInstructor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>

    <style>
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }

        .logo {
            width: 7%;
        }

        .logoAndP {
            font-family: sans-serif;
        }

        .grayColor {
            color: lightgray;
        }

        #updatebtn {
            background-color: cadetblue;
        }
    </style>
</head>
<body>
    <!-----------------------------------------------header--------------------------------------->
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>

    <!-----------------------------------------------navbar--------------------------------------->
    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>
    <!---------------------------------------content------------------------------------------------->
    <div class="container  mt-lg-4">
        <form method="post" class="m-xxl-5" asp-route-OldInsImg="@Model.Img_Id" enctype="multipart/form-data">
            <div class="col-md-6">
                <input asp-for="Ins_Id" type="hidden" /><br />
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label>Confirm Password</label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="Age"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
                <br />
            </div>

            <div class ="col-md-6">
                <label asp-for="Img_Id">Image Id</label>
                <input class="form-control" type="file" name="imageFile" />
                <span asp-validation-for="Img_Id" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="Salary"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
                <br />
            </div>

            <div class="col-md-6">
                <label asp-for="HiringDate"></label>
                <input asp-for="HiringDate" class="form-control" />
                <span asp-validation-for="HiringDate" class="text-danger"></span>
            </div>
            <input type="submit" value="Edit" class="btn text-light mt-2 mb-3" id="updatebtn" />
        </form>
    </div>

    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>

Examination_System/Views/InstructorCRUD/InsertInstructor.cshtml
@model Instructor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InsertInstructor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>
    <style>
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }

        .logo {
            width: 7%;
        }
        .logoAndP{
            font-family: sans-serif;
        }

        .grayColor{
            color: lightgray;
        }

        #Addbtn {
            background-color: cadetblue;
        }
    </style>
</head>
<body>
    <!---------------------------------------Header------------------------------------------------->
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>

    <!---------------------------------------Nav------------------------------------------------->
    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>
    <!---------------------------------------content------------------------------------------------->
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class ="col-md-6 m-3">
                <div class ="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                    <br/>
                </div>

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">

                    <label>Confirm Password</label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="Age"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="Img_Id"></label>
                    <input class="form-control" type="file" name="imageFile" />
                    <span asp-validation-for="Img_Id" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group">
                    <label asp-for="Salary"></label>
                    <input asp-for="Salary" class="form-control" />
                    <span asp-validation-for="Salary" class="text-danger"></span>
                    <br />
                </div>

                <div class="form-group mb-3">
                    <label asp-for="HiringDate"></label>
                    <input asp-for="HiringDate" class="form-control" />
                    <span asp-validation-for="HiringDate" class="text-danger"></span>
                </div>
                <input type="submit" value="Add" class="btn text-light" id="Addbtn" />
            </div>
        </form>
    </div>

    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>

Examination_System/Views/InstructorCRUD/ShowInstructors.cshtml
@model IEnumerable<Instructor>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowInstructors</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>
    <style>
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }

        .logo {
            width: 7%;
        }

        .logoAndP {
            font-family: sans-serif;
        }

        .grayColor {
            color: lightgray;
        }
    </style>
</head>
<body>
    <!-----------------------------------------------header--------------------------------------->
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>
    <!-----------------------------------------------navbar--------------------------------------->
    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>
    <!-----------------------------------------------Table--------------------------------------->

    <div class="container">
        <div class="text-center">
             <h3 class="justify-content-center mt-5">Instructors Data</h3>
            <table class="table table-bordered border-danger table-hover align-items-center justify-content-center mt-5">
    
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Email</th>   
                    <th>Address</th>
                    <th>Image ID</th>
                    <th>Salary</th>
                    <th>Hiring Date</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td colspan="10">No Instructors Found</td>
                            
                            </tr>
                        }
                }
                else
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Ins_Id</td>
                            <td>@item.Name</td>
                            <td>@item.Age</td>
                            <td>@item.Email</td>                      
                            <td>@item.Address</td>
                            @if (@item.Img_Id == null)
                            {
                                <td>-</td>
                            }
                            else
                            {
                                <td>@item.Img_Id</td>
                            }
                            <td>@item.Salary</td>
                            <td>@item.HiringDate</td>
                            <td>
                                <a asp-action="EditInstructor" asp-controller="InstructorCRUD" asp-route-id=" @item.Ins_Id" class="btn btn-primary m-1">Edit</a>
                                <a asp-action="DeleteInstructor" onclick="return confirm('Are you sure?')" asp-controller="InstructorCRUD" asp-route-id=" @item.Ins_Id" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
            </table>
            <a class="btn btn-success text-light" asp-action="InsertInstructor" asp-controller="InstructorCRUD">Add Instructor</a>
        </div>
    </div>
   
    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center mt-5">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>