Examination_System/Controllers/TrackInstructorCRUDController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class TrackInstructorCRUDController : Controller
    {
        ITIContext DB;
        public TrackInstructorCRUDController(ITIContext Db)
        {
            DB = Db;
        }
        public IActionResult ShowTrackInstructor()
        {
            var model = DB.Track_Instructor.Include(a => a.instructor).Include(a => a.Track).ToList();
            return View(model);
        }
        public IActionResult InsertTrackInstructor()
        {
            ViewBag.Track = DB.Track.ToList();
            var model = DB.Instructor.ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult InsertTrackInstructor(int Trackid, int Insid)
        {
            var TrackIns = new Track_Instructor
            {
                TrackId = Trackid,
                Ins_Id = Insid
            };
            DB.Track_Instructor.Add(TrackIns);
            DB.SaveChanges();
            return RedirectToAction("ShowTrackInstructor");
        }
        public IActionResult DeleteTrackInstructor(string idstring)
        {
            String[] ids = idstring.Split(',');
            var model = DB.Track_Instructor.SingleOrDefault(a => a.TrackId == int.Parse(ids[0]) && a.Ins_Id == int.Parse(ids[1]));
            if (model == null)
            {
                return NotFound();
            }
            else
            {
                DB.Track_Instructor.Remove(model);
                DB.SaveChanges();
                return RedirectToAction("ShowTrackInstructor");
            }

        }
    }
}

Examination_System/Views/TrackInstructorCRUD/InsertTrackInstructor.cshtml
@model IEnumerable<Instructor>
@{
    Layout = null;
    List<Track> TrackList = ViewBag.Track;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InsertTrackInstructor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <title>Add</title>

    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>

    <style>
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }

        .logo {
            width: 7%;
        }

        .logoAndP {
            font-family: sans-serif;
        }

        .grayColor {
            color: lightgray;
        }

        #Addbtn {
            background-color: cadetblue;
        }
    </style>

</head>
<body>

    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>


    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>



    <div class="container mt-lg-5">
        <form method="post">
           <div class="col-md-6">
                <div class="form-group">
    
                    <h4>Track <span class="label label-default"></span></h4>
                    <select class="form-select" name="Trackid">
                        <option selected>Select Track</option>
                        @foreach (var item in TrackList)
                        {
                            <option value="@item.TrackId">@item.Name</option>
                        }
                    </select>
                    <br />

                    <h4>Course <span class="label label-default"></span></h4>
                    <select class="form-select" name="Insid">
                        <option selected>Select Instructor</option>
                        @foreach (var item in Model)
                        {
                            <option value="@item.Ins_Id">@item.Name</option>
                        }
                    </select>
                    </br>
                    <input type="submit" value="Add" class="btn text-light" id="Addbtn" />
                </div>
            </div>
        </form>
    </div>

    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center mt-5">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>

Examination_System/Views/TrackInstructorCRUD/ShowTrackInstructor.cshtml
@model IEnumerable<Track_Instructor>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowTrackInstructor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>
    <style>
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }

        .logo {
            width: 7%;
        }

        .logoAndP {
            font-family: sans-serif;
        }

        .grayColor {
            color: lightgray;
        }
    </style>
</head>
<body>

    <!-----------------------------------------------header--------------------------------------->
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>
    <!-----------------------------------------------navbar--------------------------------------->
    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>
    <!-----------------------------------------------Table--------------------------------------->

    <div class="container">
        <div class="text-center">
            <h3 class="justify-content-center mt-5">Instructors Tracks Data</h3>
            <table class="table table-bordered table-hover border-danger align-items-center justify-content-center mt-5">


                <thead>
                    <tr>
                        <th>Track</th>
                        <th>Instructor</th>
                        <th>Operation</th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count() == 0)
                    {
                        <tr>
                            <td colspan="3">No Data Found</td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Track.Name</td>
                                <td>@item.instructor.Name</td>
                                <td>
                                    <a class="btn btn-danger" asp-action="DeleteTrackInstructor" asp-controller="TrackInstructorCRUD" onclick="return confirm (' Are you sure?')" asp-route-idstring="@String.Join(",", item.TrackId, item.Ins_Id)">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <a asp-action="InsertTrackInstructor" asp-controller="TrackInstructorCRUD" class="btn btn-success">Add</a>
    
        </div>
    </div>

    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center mt-5">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>