Examination_System/Models/Instructor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public class Instructor
    {
        [Key]
        public int Ins_Id { get; set; }
        [StringLength(20)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(50)]
        [RegularExpression(@"[a-zA-Z0-9_]+@[a-zA-Z]+.[a-zA-Z]{2,}", ErrorMessage = "Please enter a valid email address.")]
        public string Email { get; set; }
        public string Password { get; set; }
        [NotMapped] // ==> won't go to the DB
        [Compare("Password")]
        public required string ConfirmPassword { get; set; }
        public int Age { get; set; }
        public string? Img_Id { get; set; }
        public float Salary { get; set; }
        [DataType(DataType.Date)] 
        public DateTime HiringDate { get; set; }

        public  Track? Track { get; set; }
        public  ICollection<Track_Instructor> Track_Instructor { get; } = new HashSet<Track_Instructor>();
        public  ICollection<InstructorCourse> InstructorCourse { get; } = new HashSet<InstructorCourse>();
    }
}

Examination_System/Controllers/AdminController.cs
using Examination_System.Models;
using Examination_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class AdminController : Controller
    {
        ITIContext db;

        public AdminController(ITIContext _db)
        {
            db = _db;
        }
        //1st report
        public IActionResult theStudentsInformationAccordingToTrackId(int TrackID)
        {
            var model = db.Student.Where(s => s.Track.TrackId == TrackID);
            return View(model);
        }

        //2ns report
        public IActionResult takesStdIDAndReturnsGradesInAllCourses(int StdID)
        {
            var studentGrades = from SC in db.StudentCourse
                                join C in db.Course on SC.CrsId equals C.Course_ID
                                where SC.StudentId == StdID
                                select new DisplayStudentGrades
                                {
                                    CourseName = C.Name,
                                    stdId = SC.StudentId,
                                    Grade = SC.Grade

                                };
            // Pass the data to the view
            return View(studentGrades.ToList());
        }
        //3rd report
        public IActionResult NameOfCourses_ForInstructor_NumOfStudent(int InsID)
        {
            var model = db.Instructor
                .Include(c => c.InstructorCourse)
                .ThenInclude(c => c.Course)
                .ThenInclude(c => c.studentCourses)
                .SingleOrDefault(x => x.Ins_Id == InsID );
            return View(model);
        }
        //4th report
        public IActionResult TopicsData_By_CourseID(int CoursesID)
        {
            var model = db.Course.Include(a => a.Topics).SingleOrDefault(x => x.Course_ID == CoursesID);
            return View(model);
        }

        public IActionResult GetQuestions_Choices(int ExId)
        {
            var model = db.Exam.Include(q => q.Questions).SingleOrDefault(x => x.Exam_ID == ExId);
            return View(model);
        }

        public IActionResult GetQuestions_Stu_Answers(int ExId, int StuId)
        {
            var model = db.Exam.Include(q => q.Questions).ThenInclude(s => s.StudentAnswers).SingleOrDefault(x => x.Exam_ID == ExId);
            ViewBag.StuId = StuId;
            return View(model);
        }
    }
}

Examination_System/Controllers/ExamCRUDController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;

namespace Examination_System.Controllers
{
    public class ExamCRUDController : Controller
    {
        ITIContext DB;
        public ExamCRUDController(ITIContext Db)
        {
            DB = Db;
        }


        public IActionResult GetExams()
        {
            var model = DB.Exam.ToList();
            return View(model);
        }
        public IActionResult EditExams(int Exam_ID)
        {
            ViewBag.coursesList = DB.Course.ToList();
            if (Exam_ID == null)
            {
                return BadRequest();
            }

            var model = DB.Exam.FirstOrDefault(s => s.Exam_ID == Exam_ID);

            return View(model);
        }

        [HttpPost]

        public IActionResult EditExams(Exam exam)
        {
            DB.Exam.Update(exam);
            DB.SaveChanges();
            return RedirectToAction("GetExams");
        }
        public IActionResult DeleteExams(int id)
        {
            var exam = DB.Exam.SingleOrDefault(a => a.Exam_ID == id);
            if (exam == null)
            {
                return NotFound(); // Or handle the case where the exam doesn't exist
            }

            var questions = DB.Question.Where(sa => sa.Exam_ID == exam.Exam_ID).ToList();
            foreach (var question in questions)
            {
                var studentAnswers = DB.StudentAnswer.Where(s => s.Ques_ID == question.Ques_ID).ToList();
                foreach (var answer in studentAnswers)
                {
                    DB.StudentAnswer.Remove(answer);
                }
                DB.Question.Remove(question);
            }

            // Then delete the exam
            DB.Exam.Remove(exam);
            DB.SaveChanges();
            return RedirectToAction("GetExams");
        }
        public IActionResult CreateExams()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateExams(Exam exam)
        {

            DB.Exam.Add(exam);
            DB.SaveChanges();
            return RedirectToAction("GetExams");

        }

    }
}

Examination_System/Controllers/HomePageController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class HomePageController : Controller
    {
        ITIContext db;

        public HomePageController(ITIContext _db)
        {
            db = _db;
        }

        public IActionResult ShowCourses(int id)
        {
            var model = db.Student.Include(s => s.CourseStudents).ThenInclude(cs => cs.course).ThenInclude(e => e.Exam).SingleOrDefault(s => s.Id == id);
            var track = db.Track.SingleOrDefault(t => t.TrackId == model.TrackId);
            ViewBag.track = track;
            return View(model);
        }
        public IActionResult Instructor(int id)
        {
            var model = db.Instructor.SingleOrDefault(s => s.Ins_Id == id);
            return View(model);
        }


    }
}

Examination_System/Controllers/StudentController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class StudentController : Controller
    {

        ITIContext DB;
        public StudentController(ITIContext db)
        {
            DB = db;
        }

        public IActionResult GenerateQuestions(int stdID, int CrsId)
        {
            var questions = DB.Question
               .Include(q => q.Exam) 
               .Where(q => q.Exam.Course_ID == CrsId)
               .ToList();

            Random rand = new Random();
            int n = questions.Count;
            while (n > 1)
            {
                n--;
                int k = rand.Next(n + 1);
                var value = questions[k];
                questions[k] = questions[n];
                questions[n] = value;
            }

            ViewBag.StdId = stdID;
            ViewBag.CrsId = CrsId;
            var Em = DB.Exam.SingleOrDefault(e => e.Course_ID == CrsId);
            ViewBag.duration = Em.Duration;
            var StdName = DB.Student.SingleOrDefault(s => s.Id == stdID);
            ViewBag.StudentName = StdName.Name;
            var course = DB.Course.SingleOrDefault(c => c.Course_ID == CrsId);
            ViewBag.CrsName = course.Name;
            return View(questions);
        }
    }
}

Examination_System/Controllers/TrackCRUDController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class TrackCRUDController : Controller
    {
        ITIContext db;

        public TrackCRUDController(ITIContext _db)
        {
            db = _db;
        }
        public IActionResult TrackIndex()  //fn to display ist of Track
        {
            var model = db.Track.Include(a => a.Instructor).ToList(); ; // list of courses
            return View(model);
        }

        public IActionResult CreateTrack()
        {
            // Get the list of instructor IDs who are already supervisors in existing tracks
            var existingSupervisorIds = db.Track.Select(t => t.Supervisor).Distinct().ToList();

            // Filter the list of instructors to exclude those who are already supervisors
            var availableInstructors = db.Instructor.Where(i => !existingSupervisorIds.Contains(i.Ins_Id)).ToList();

            ViewBag.Instructorlist = availableInstructors;
            return View();
        }

        [HttpPost]
        public IActionResult CreateTrack(Track trk)
        {
            db.Track.Add(trk);
            db.SaveChanges();
            return RedirectToAction("TrackIndex");
        }

        public IActionResult EditTrack(int TrackId)
        {
            // Get the list of instructor IDs who are already supervisors
            var existingSupervisorIds = db.Track.Select(t => t.Supervisor).Distinct().ToList();

            // Filter the list of instructors to exclude those who are already supervisors
            var availableInstructors = db.Instructor.Where(i => !existingSupervisorIds.Contains(i.Ins_Id)).ToList();
            ViewBag.Instructorlist = availableInstructors;

            if (TrackId == null)
            {
                return BadRequest();
            }

            var model = db.Track.SingleOrDefault(a => a.TrackId == TrackId);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult EditTrack(Track trk)
        {
            db.Track.Update(trk);
            db.SaveChanges();
            return RedirectToAction("TrackIndex");
        }

        public IActionResult DeleteTrack(int TrackId)
        {
            var model = db.Track.SingleOrDefault(a => a.TrackId == TrackId);
            var Track_ins = db.Track_Instructor.Where(sa => sa.TrackId == TrackId).ToList();
            foreach (var answer in Track_ins)
            {
                db.Track_Instructor.Remove(answer);
            }
            var Stu = db.Student.Where(sa => sa.TrackId == TrackId).ToList();
            foreach (var answer in Stu)
            {
                answer.TrackId = null;
                db.SaveChanges();
            }
            db.Track.Remove(model);
            db.SaveChanges();
            return RedirectToAction("TrackIndex");

        }

    }
}

Examination_System/Views/HomePage/Instructor.cshtml
@model Instructor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ITI Instructor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script>

    <style>
        .sidenav a:hover{
            background-color: #7f7e80;
        }
        .header {
            padding: 8px 8%;
            background-color: darkred;
        }
        .logo {
            width: 7%;
        }
        .img1:hover{
            opacity:50%
        }
        .img1{
            height:200px;
        }
        .submit{
            background-color:darkred;
            color:antiquewhite;
        }
        .exp{
            height: 150px;
        }
        .div1{
            margin-left:40%;
            margin-right :20%;
        }

        .logoAndP {
            font-family: sans-serif;
        }

        .grayColor {
            color: lightgray;
        }

        .InstImg {
            width: 300px;
            height: 300px;
            object-fit: cover;
        }

    </style>
</head>
<body  style="height:100vh;">

    <!-----------------------------------------------sidebar--------------------------------------->
    <div class="sidenav position-absolute pt-2" style="height:90%;width:200px;top:115px;left:0;background-color: #f2f7f4;">
        <div class="mt-3" style="margin-left:15px;width:170px;">
            
            <a asp-action="ShowInstructorCourse" asp-controller="InstructorCourseCRUD" class="btn btn-outline-secondary btn-sm">Show Instructor Courses</a>
            <br />
            <br />
            <a asp-action="ShowTrackInstructor" asp-controller="TrackInstructorCRUD" class="btn btn-outline-secondary btn-sm">Show Track Instructors</a>
            <br />
            <br />
            <a asp-action="ShowStudentCourse" asp-controller="StudentCourseCRUD" class="btn btn-outline-secondary btn-sm">Show Student Courses</a>
            <br />
            <br />
            <a asp-action="ShowInstructors" asp-controller="InstructorCRUD" class="btn btn-outline-secondary btn-sm">Show Instructors</a>
            <br />
            <br />
            <a asp-action="ShowStudents" asp-controller="StudentCRUD" class="btn btn-outline-secondary btn-sm">Show Students</a>
            <br />
            <br />
            <a asp-action="CourseIndex" asp-controller="CourseCRUD" class="btn btn-outline-secondary btn-sm">Show Courses</a>
            <br />
            <br />
            <a asp-action="TrackIndex" asp-controller="TrackCRUD" class="btn btn-outline-secondary btn-sm">Show Tracks</a>
            <br />
            <br />
            <a asp-action="GetExams" asp-controller="ExamCRUD" class="btn btn-outline-secondary btn-sm">Show Exams</a>

        </div>

    </div>
    <!-----------------------------------------------header--------------------------------------->
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>
    <!-----------------------------------------------navbar--------------------------------------->

    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>
    <!------------------------------------------------------ Instructor Info ------------------------------------------------------>
    <section class="text-center mt-5 mb-5 w-50 m-auto">
        @if (@Model.Img_Id != null)
        {
            <img src="/images/Instructors/@Model.Img_Id" class="InstImg rounded-circle border border-5 border-light shadow-lg" />
        }
        else
        {
            <img src="/images/anonymous_person.jpg" class="InstImg rounded-circle border border-5 border-light shadow-lg" />
        }
        <h1>@Model.Name</h1>
        <h6 class="text-secondary">@Model.Email</h6>
    </section>


    <!-----------------------------------------------content--------------------------------------->

        <div class="row d-flex flex-wrap justify-content-around align-items-center "style="margin:30px; margin-left:200px;" >

            <div class="card mb-5" style="width: 30%;">
                <img class="img1" src="~/images/5.jpg" class="card-img-top " alt="image1" />
                <div class="card-body">
                    <h5 class="card-title">Instructor Courses</h5>
                    <p class="card-text">Enter Instructor Id to show courses</p>
                    <form method="post" asp-controller="Admin" asp-action="NameOfCourses_ForInstructor_NumOfStudent">
                        <input type="text" name="InsID" placeholder="Instructor ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>


            <div class="card mb-5" style="width: 30%;">
                <img class="img1" src="~/images/1.jpg" class="card-img-top " alt="image1" />
                <div class="card-body">
                <h5 class="card-title">Track Students</h5>
                    <p class="card-text">Enter track Id to get students</p>
                    <form method="post" asp-controller="Admin" asp-action="theStudentsInformationAccordingToTrackId">
                        <input type="text" name="TrackID" placeholder="Track ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>

            <div class="card mb-5" style="width: 30%;">
                <img class="img1" src="~/images/3.webp" class="card-img-top " alt="image1" />
                <div class="card-body">
                    <h5 class="card-title">Student Grades</h5>
                    <p class="card-text">Enter student Id to show grades</p>
                    <form method="post" asp-controller="Admin" asp-action="takesStdIDAndReturnsGradesInAllCourses">
                        <input type="text" name="StdID" placeholder="Student ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>  

            <div class="card mb-5" style="width: 30%;">
                <img class="img1" src="~/images/4.png" class="card-img-top " alt="image1" />
                <div class="card-body">
                    <h5 class="card-title">Course topics</h5>
                    <p class="card-text">Enter Course Id to show Topics</p>
                    <form method="post" asp-controller="Admin" asp-action="TopicsData_By_CourseID">
                        <input type="text" name="CoursesID" placeholder="Course ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>

            <div class="card mb-5" style="width: 30%;">
                <img class="img1" src="~/images/2.jpg" class="card-img-top " alt="image1" />
                <div class="card-body">
                    <h5 class="card-title">Exam</h5>
                    <p class="card-text">Enter exam Id to get the exam</p>
                    <form method="post" asp-controller="Admin" asp-action="GetQuestions_Choices">
                        <input type="text" name="ExId" placeholder="Exam ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>

            <div class="card mb-5" style="width: 30%;">
                <img class="img1 exp"  src="~/images/10.webp" class="card-img-top " alt="image1" />
                <div class="card-body">
                    <h5 class="card-title">Student exam</h5>
                    <p class="card-text">Enter Student Id to get the student exam with answers</p>
                    <form method="post" asp-controller="Admin" asp-action="GetQuestions_Stu_Answers">
                        <input type="text" name="ExId" placeholder="Exam ID" />
                        <input type="text" name="StuId" placeholder="Student ID" />
                        <input type="submit" value="Show" class="submit btn mt-1" />
                    </form>
                </div>
            </div>

        </div>
    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center">
        <div class="logoAndP w-50">
            <img class="w-25" src="~/images/WhiteLogo4.svg" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>

Examination_System/Views/HomePage/ShowCourses.cshtml
@model Student
@{
    Layout = null;
    Track tr = ViewBag.track;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowCourses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/d3bc0f0f7a.js" crossorigin="anonymous"></script> 
    <style>
        .header{
            padding: 8px 8%;
            background-color: darkred;
        }
        .logo{
            width:7%;
        }

        .studentImg{
            width:300px;
            height:300px;
            object-fit: cover;
        }

        .course {
            position: relative;
            height: 450px;
            font-family: sans-serif;
            letter-spacing: 4px;
            font-weight:bolder;
        }

        .course::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-image: url('/Images/iti.jpg');
            background-size: cover;
            background-position: center bottom;
            background-repeat: no-repeat;
            filter: blur(2px);
            z-index: -1; 
        }

        .logoAndP{
            font-family: sans-serif;
        }

        .grayColor{
            color: lightgray;
        }
    </style>
</head>
<body>
    <!------------------------------------------------------ Header ------------------------------------------------------>
    <header class="header fs-6 d-flex justify-content-between align-items-center text-light">
        <section class="d-flex">
            <div> <a class="text-light text-decoration-none" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a></div>
            <div> <i class="fa-solid fa-mobile-screen-button ms-3"></i> 17002</div>
        </section>
        <section class="d-flex">
            <a class="text-light" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
            <a class="text-light" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
            <a class="text-light" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
            <a class="text-light" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
        </section>
    </header>

    <!------------------------------------------------------ NavBar ------------------------------------------------------>
    <nav class="navbar bg-light sticky-top d-flex justify-content-around align-items-center">
        <img src="/Images/logo.png" class="logo" />
        <div class="d-flex ms-4 align-items-center fw-medium">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
            <div class="ps-2 ms-5"><a class="text-decoration-none bg-secondary bg-gradient btn text-light p-2" asp-controller="Login" asp-action="LogOut">Logout</a></div>
        </div>
    </nav>

    <!------------------------------------------------------ Student Info ------------------------------------------------------>
    <section class="text-center mt-5 mb-5 w-50 m-auto">
        @if(@Model.Image_ID != null)
        {
            <img src="/Images/Students/@Model.Image_ID" class="studentImg rounded-circle border border-5 border-light shadow-lg" />
        }
        else
        {
            <img src="/Images/anonymous_person.jpg" class="studentImg rounded-circle border border-5 border-light shadow-lg" />
        }
        <h1>@Model.Name</h1>
        <h6 class="text-secondary">@Model.Email</h6>
        @if (tr.Name != null)
        {
            <p><span class="text-warning">@tr.Name</span> Track</p>
            <p>@tr.Description</p>
        }
    </section>

    <!------------------------------------------------------ ITI ------------------------------------------------------>
    <section>
        <div class="course text-white d-flex align-items-center ps-5">
            <div>
                <p>Every challenge you overcome brings you closer to success.</p>
                <h1>Empower Yourself Today</h1>
            </div>
        </div>
    </section>

    <!------------------------------------------------------ Courses ------------------------------------------------------>
    <section class="my-5 w-50 m-auto">
        @foreach (var item in Model.CourseStudents)
        {
            <div class="mb-3 shadow-lg bg-light rounded p-4 ">
                <div>
                    <h2>@item.course.Name</h2>
                    <p>This course is @item.course.Hours Hours</p>
                    <p>The Exam duration of this course is: @item.course.Exam.Duration</p>
                    <a asp-action="GenerateQuestions" asp-controller="Student" asp-route-stdID="@item.StudentId" asp-route-CrsId="@item.CrsId" class="btn btn-primary text-light">Go to Exam</a>
                </div>
            </div>
        }
    </section>

    <!------------------------------------------------------ Footer ------------------------------------------------------>
    <footer class="header d-flex text-light justify-content-between align-items-center">
        <div class="logoAndP w-50">
            <img class="w-25" src="/Images/whiteLogo.png" />
            <p class="grayColor mt-2">Over 30 years, ITI has kept updating its training portfolio thru continuous monitoring for the future global tech trends, as well as the country’s national and mega projects, hence; sustaining its graduates’ employment percentage to 85 prior their graduation.</p>
        </div>
        <div>
            <h3 class="mb-4">KEEP IN TOUCH</h3>
            <div>
                <a class="text-decoration-none grayColor" href="https://iti.gov.eg/home"><i class="fa-regular fa-envelope"></i> ITI Website</a>
                <span>
                    <i class="fa-solid fa-mobile-screen-button ms-3 grayColor"></i> 17002
                    <section class="mt-3 d-flex">
                        <a class="grayColor" href="https://twitter.com/itichannel2"><i class="fa-brands fa-twitter ms-4"></i></a>
                        <a class="grayColor" href="https://www.facebook.com/itichannel/"><i class="fa-brands fa-facebook ms-4"></i></a>
                        <a class="grayColor" href="https://www.youtube.com/user/itichannel"><i class="fa-brands fa-youtube ms-4"></i></a>
                        <a class="grayColor" href="https://eg.linkedin.com/school/information-technology-institute-iti-/"><i class="fa-brands fa-linkedin ms-4"></i></a>
                    </section>
                </span>
            </div>
        </div>
    </footer>

    <div class="px-5 bg-light d-flex justify-content-between">
        <p>Copyright ©2022 All Rights Reserved. Information Technology Institute (ITI).</p>
        <p>Terms of Use . Privacy Policy</p>
    </div>
</body>
</html>