Examination_System/Controllers/HomePageController.cs
using Examination_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Controllers
{
    public class HomePageController : Controller
    {
        ITIContext db;

        public HomePageController(ITIContext _db)
        {
            db = _db;
        }

        public IActionResult ShowCourses(int id)
        {
            var model = db.Student.Include(s => s.CourseStudents).ThenInclude(cs => cs.course).ThenInclude(e => e.Exam).SingleOrDefault(s => s.Id == id);
            var track = db.Track.SingleOrDefault(t => t.TrackId == model.TrackId);
            ViewBag.track = track;
            return View(model);
        }
        public IActionResult Instructor(int id)
        {
            var model = db.Instructor.SingleOrDefault(s => s.Ins_Id == id);
            return View(model);
        }


    }
}

Examination_System/Controllers/ViewStudentAnswersController.cs
using Examination_System.Models;
using Examination_System.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Examination_System.Controllers
{
    public class ViewStudentAnswersController : Controller
    {
        ITIContext DB;
        public ViewStudentAnswersController(ITIContext Db)
        {
            DB = Db;
        }
        public IActionResult Index(int ExamId, int STD_ID ,int CRS_ID)
        {
            int stdId = STD_ID;
            int Examid = ExamId;
            var StudentAnswers = from Question in DB.Question
                                 join StudentAnswer in DB.StudentAnswer on Question.Ques_ID equals StudentAnswer.Ques_ID
                                 where Question.Exam_ID == Examid && StudentAnswer.Stud_Id == stdId
                                 select new DisplayStudentAnswers
                                 {
                                     Ques_ID = Question.Ques_ID,
                                     Quest = Question.Quest,
                                     Corr_Answer = Question.Corr_Answer,
                                     OPt1_Answer = Question.OPt1_Answer,
                                     OPt2_Answer = Question.OPt2_Answer,
                                     OPt3_Answer = Question.OPt3_Answer,
                                     Student_Answer = StudentAnswer.Student_Answer,
                                     If_Correct = StudentAnswer.If_Correct,
                                     type=Question.Type
                                 };
            var crsName = DB.Course.SingleOrDefault(c => c.Course_ID == CRS_ID);
            ViewBag.CrsName= crsName.Name;
            var Std = DB.Student.SingleOrDefault(s => s.Id == STD_ID);
            ViewBag.StdName = Std.Name;
            var stdCrs = DB.StudentCourse.SingleOrDefault(s => s.StudentId == STD_ID && s.CrsId == CRS_ID);
            ViewBag.Grade = stdCrs.Grade;
            ViewBag.STD_ID = STD_ID;
            return View(StudentAnswers.ToList());
        }
    }
}

Examination_System/Views/ViewStudentAnswers/Index.cshtml
@model IEnumerable<Examination_System.ViewModels.DisplayStudentAnswers>

@{
    var Duration = ViewBag.Duration;
    var StdName = ViewBag.StdName;
    var CrsName = ViewBag.CrsName;
    var STD_ID = ViewBag.STD_ID;
    float grade=ViewBag.Grade;
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GenerateQuestions</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            padding: 20px;
            margin-right:20%;
            margin-left: 20%;
        }

        .question-container {
            margin-bottom: 20px;
        }

        .options-container {
            padding-left: 20px;
        }

        .option-label {
            margin-bottom: 5px;
            display: block;
        }

        .ViewDetails{
            background-color:darkred;
            height:170px;
            text-align:center;
            color:floralwhite;
            margin-bottom:1cm;
            padding:20px;

        }

        .p-3 {
            border: 2px solid darkred;
        }

        .DarkredBtn{
            background-color:darkred;
        }
        .Correct{
            background-color:mediumseagreen;
        }

        .Wrong{
            background-color:firebrick;
        }
    </style>
</head>
<body>
    <div class="ViewDetails">
        <h3> Student Name : @StdName</h3>
        <h3>Course Name : @CrsName</h3>
        <h3> Student Grade:@grade</h3>

    </div>
    <form method="post">
        @foreach (var item in Model)
        {
            <div class="question-container">

                @if (item.type == "MCQ")
                {
                    if (item.If_Correct == true)
                    {
                        <p><strong>@item.Quest : 1/1 </strong> </p>

                        <div class="options-container d-flex flex-column mb-3">
                            <label class="p-3 bg-opacity-10 Correct ">
                            <input type="radio" /> @item.Corr_Answer
                        </label>

                        <label class="p-3 bg-opacity-10  ">
                            <input type="radio"  /> @item.OPt1_Answer
                        </label>
                        <label class="p-3 bg-opacity-10  ">
                                <input type="radio" /> @item.OPt2_Answer
                            </label>
                        <label class="p-3 bg-opacity-10  ">
                                <input type="radio" /> @item.OPt3_Answer
                            </label>
                        </div>
                    }
                    else
                    {
                        <p><strong>@item.Quest : 0/1</strong> </p>

                        <div class="options-container d-flex flex-column mb-3">
                            <label class="p-3 bg-opacity-10 Correct ">
                                <input type="radio"  /> @item.Corr_Answer
                            </label>

                            <label class="p-3 bg-opacity-10 Wrong ">
                                <input type="radio" /> @item.Student_Answer
                            </label>
                            <label class="p-3 bg-opacity-10  ">
                                <input type="radio" /> @item.OPt2_Answer
                            </label>
                            <label class="p-3 bg-opacity-10  ">
                                <input type="radio" /> @item.OPt3_Answer
                            </label>
                        </div>
                    }
                }
                else if (item.type == "TF")
                {
                    if (item.If_Correct)
                    {
                        <p><strong>@item.Quest : 1/1</strong> </p>

                        <div class="options-container  d-flex flex-column mb-3">
                            <label class="p-3 bg-opacity-10 Correct ">
                                <input type="radio"  /> @item.Corr_Answer
                            </label>
                        <label class="p-3 bg-opacity-10  ">
                                <input type="radio" /> @item.OPt1_Answer
                            </label>
                        </div>
                    }
                    else
                    {
                        <p><strong>@item.Quest : 0/1</strong> </p>

                        <div class="options-container  d-flex flex-column mb-3">
                            <label class="p-3 bg-opacity-10 Correct ">
                                <input type="radio"  /> @item.Corr_Answer
                            </label>
                            <label class="p-3 bg-opacity-10 Wrong ">
                                <input type="radio"  /> @item.Student_Answer
                            </label>
                        </div>
                    }
                }

            </div>

        }
    </form>
    <a class="DarkredBtn text-light p-2 rounded" asp-controller="HomePage" asp-action="ShowCourses" asp-route-id="@STD_ID">Go Home</a>
</body>
</html>